class AIPipeline:
    def __init__(self):
        self.knowledge_base = [
            {'title':'Help Center','content':'Use the sidebar to open chats and analytics.'},
            {'title':'Safety','content':'Moderation flags toxic content before delivery.'},
        ]
    def classify(self, text: str) -> str:
        lowered = text.lower()
        if any(x in lowered for x in ['spam','buy now','free money']):
            return 'spam'
        if any(x in lowered for x in ['hate','idiot','stupid']):
            return 'toxic'
        return 'clean'
    def smart_reply(self, text: str):
        if 'hello' in text.lower():
            return ['Hello!','How can I assist?','Great to hear from you.']
        return ['Tell me more.','I can help with that.','Let me know what you need.']
    def summarise(self, messages):
        return f'Summary over {len(messages)} messages generated by the AI workflow.'
    def search(self, query: str):
        return [item for item in self.knowledge_base if query.lower() in item['title'].lower() or query.lower() in item['content'].lower()]
